[package]
name = "adventofcode-2017"
version = "0.1.0"
authors = ["Aaron McLeod <aaron.g.mcleod@gmail.com>"]

[dependencies]
read_input = { path = "./read_input/" }

[[bin]]
name = "3"
path = "3/main.rs"